#---- extra proeprties of dsobject or parent container dsobject-------------------------------	 
[subscription.obj.props]
#object properties : eq. <property_name>,...

[subscription.parent.props]
#parent container properties : eq. <property_name>,...etc

[subscription.mail.others]
# extra section

#---- in plaint Text -----------------------------------------	 
[subscription.mail.subject]
#subject section
{event.message.subject}

[subscription.mail.header]
#header section in plain text form
{event.message.header}

[subscription.mail.body]
#message body section in plain text form

	URL : {handle_url}
	{label.title} : {title}
	{label.summary} : {summary}
	{label.description} : {description}
	{label.abstract} : {abstract}
	{label.summary} : {revision_comments}
	{label.handle} : {handle}
	{label.create_date} : {create_date}
	Owner : {owner.username}

[subscription.mail.footer]
#footer section in plain text form
#This notification was generated by {subscription.handle}\n\t{subscription.handle_url}
{event.message.footer}

[subscription.mail.misc]
#appendix after footer section
{event.message.misc}

#---- in HTML -----------------------------------------	 
[subscription.mail.header.html]
#header section in html form
#<P>The properties of the following {classname} was edited by {emitter.username} on {event_time}
<p>{event.message.header.html}

[subscription.mail.body.html]
#message body section in html form
<br><TABLE CELLPADDING=4><TR VALIGN="TOP">
<TD ALIGN="CENTER"><img src="{icon} "><br></TD>
<TD><A HREF="{handle_url} ">{title}</A>
	<br>{summary}
	<br>{description}
	<br><I>Appears In: </I>&nbsp;<A HREF="{parent.handle_url}">{parent.title}</A>
	<br></TD>
<TD><A HREF="{owner.handle_url}">{owner.username}</A></TD>
<TD>{create_date}</TD>
<TD><A HREF="{parent.handle_url}">Props</A></TD>
</TR></TABLE><br>

[subscription.mail.footer.html]
#footer section in html form
{event.message.footer.html}

